/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as BooksBookIdIndexRouteImport } from './routes/books.$bookId.index'
import { Route as BooksBookIdSessionsSessionIdRouteImport } from './routes/books.$bookId.sessions.$sessionId'
import { Route as BooksBookIdSessionsSessionIdIndexRouteImport } from './routes/books.$bookId.sessions.$sessionId.index'
import { Route as BooksBookIdSessionsSessionIdReviewsReviewIdRouteImport } from './routes/books.$bookId.sessions.$sessionId.reviews.$reviewId'
import { Route as BooksBookIdSessionsSessionIdReviewsReviewIdIndexRouteImport } from './routes/books.$bookId.sessions.$sessionId.reviews.$reviewId.index'
import { Route as BooksBookIdSessionsSessionIdReviewsReviewIdNewRouteImport } from './routes/books.$bookId.sessions.$sessionId.reviews.$reviewId.new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdIndexRoute = BooksBookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdSessionsSessionIdRoute =
  BooksBookIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => BooksBookIdRoute,
  } as any)
const BooksBookIdSessionsSessionIdIndexRoute =
  BooksBookIdSessionsSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BooksBookIdSessionsSessionIdRoute,
  } as any)
const BooksBookIdSessionsSessionIdReviewsReviewIdRoute =
  BooksBookIdSessionsSessionIdReviewsReviewIdRouteImport.update({
    id: '/reviews/$reviewId',
    path: '/reviews/$reviewId',
    getParentRoute: () => BooksBookIdSessionsSessionIdRoute,
  } as any)
const BooksBookIdSessionsSessionIdReviewsReviewIdIndexRoute =
  BooksBookIdSessionsSessionIdReviewsReviewIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BooksBookIdSessionsSessionIdReviewsReviewIdRoute,
  } as any)
const BooksBookIdSessionsSessionIdReviewsReviewIdNewRoute =
  BooksBookIdSessionsSessionIdReviewsReviewIdNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => BooksBookIdSessionsSessionIdReviewsReviewIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
  '/books/$bookId/sessions/$sessionId': typeof BooksBookIdSessionsSessionIdRouteWithChildren
  '/books/$bookId/sessions/$sessionId/': typeof BooksBookIdSessionsSessionIdIndexRoute
  '/books/$bookId/sessions/$sessionId/reviews/$reviewId': typeof BooksBookIdSessionsSessionIdReviewsReviewIdRouteWithChildren
  '/books/$bookId/sessions/$sessionId/reviews/$reviewId/new': typeof BooksBookIdSessionsSessionIdReviewsReviewIdNewRoute
  '/books/$bookId/sessions/$sessionId/reviews/$reviewId/': typeof BooksBookIdSessionsSessionIdReviewsReviewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/books': typeof BooksIndexRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
  '/books/$bookId/sessions/$sessionId': typeof BooksBookIdSessionsSessionIdIndexRoute
  '/books/$bookId/sessions/$sessionId/reviews/$reviewId/new': typeof BooksBookIdSessionsSessionIdReviewsReviewIdNewRoute
  '/books/$bookId/sessions/$sessionId/reviews/$reviewId': typeof BooksBookIdSessionsSessionIdReviewsReviewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
  '/books/$bookId/sessions/$sessionId': typeof BooksBookIdSessionsSessionIdRouteWithChildren
  '/books/$bookId/sessions/$sessionId/': typeof BooksBookIdSessionsSessionIdIndexRoute
  '/books/$bookId/sessions/$sessionId/reviews/$reviewId': typeof BooksBookIdSessionsSessionIdReviewsReviewIdRouteWithChildren
  '/books/$bookId/sessions/$sessionId/reviews/$reviewId/new': typeof BooksBookIdSessionsSessionIdReviewsReviewIdNewRoute
  '/books/$bookId/sessions/$sessionId/reviews/$reviewId/': typeof BooksBookIdSessionsSessionIdReviewsReviewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/books/$bookId'
    | '/books/'
    | '/books/$bookId/'
    | '/books/$bookId/sessions/$sessionId'
    | '/books/$bookId/sessions/$sessionId/'
    | '/books/$bookId/sessions/$sessionId/reviews/$reviewId'
    | '/books/$bookId/sessions/$sessionId/reviews/$reviewId/new'
    | '/books/$bookId/sessions/$sessionId/reviews/$reviewId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/books'
    | '/books/$bookId'
    | '/books/$bookId/sessions/$sessionId'
    | '/books/$bookId/sessions/$sessionId/reviews/$reviewId/new'
    | '/books/$bookId/sessions/$sessionId/reviews/$reviewId'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/settings'
    | '/books/$bookId'
    | '/books/'
    | '/books/$bookId/'
    | '/books/$bookId/sessions/$sessionId'
    | '/books/$bookId/sessions/$sessionId/'
    | '/books/$bookId/sessions/$sessionId/reviews/$reviewId'
    | '/books/$bookId/sessions/$sessionId/reviews/$reviewId/new'
    | '/books/$bookId/sessions/$sessionId/reviews/$reviewId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  BooksBookIdRoute: typeof BooksBookIdRouteWithChildren
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId/': {
      id: '/books/$bookId/'
      path: '/'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof BooksBookIdIndexRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/sessions/$sessionId': {
      id: '/books/$bookId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/books/$bookId/sessions/$sessionId'
      preLoaderRoute: typeof BooksBookIdSessionsSessionIdRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/sessions/$sessionId/': {
      id: '/books/$bookId/sessions/$sessionId/'
      path: '/'
      fullPath: '/books/$bookId/sessions/$sessionId/'
      preLoaderRoute: typeof BooksBookIdSessionsSessionIdIndexRouteImport
      parentRoute: typeof BooksBookIdSessionsSessionIdRoute
    }
    '/books/$bookId/sessions/$sessionId/reviews/$reviewId': {
      id: '/books/$bookId/sessions/$sessionId/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/books/$bookId/sessions/$sessionId/reviews/$reviewId'
      preLoaderRoute: typeof BooksBookIdSessionsSessionIdReviewsReviewIdRouteImport
      parentRoute: typeof BooksBookIdSessionsSessionIdRoute
    }
    '/books/$bookId/sessions/$sessionId/reviews/$reviewId/': {
      id: '/books/$bookId/sessions/$sessionId/reviews/$reviewId/'
      path: '/'
      fullPath: '/books/$bookId/sessions/$sessionId/reviews/$reviewId/'
      preLoaderRoute: typeof BooksBookIdSessionsSessionIdReviewsReviewIdIndexRouteImport
      parentRoute: typeof BooksBookIdSessionsSessionIdReviewsReviewIdRoute
    }
    '/books/$bookId/sessions/$sessionId/reviews/$reviewId/new': {
      id: '/books/$bookId/sessions/$sessionId/reviews/$reviewId/new'
      path: '/new'
      fullPath: '/books/$bookId/sessions/$sessionId/reviews/$reviewId/new'
      preLoaderRoute: typeof BooksBookIdSessionsSessionIdReviewsReviewIdNewRouteImport
      parentRoute: typeof BooksBookIdSessionsSessionIdReviewsReviewIdRoute
    }
  }
}

interface BooksBookIdSessionsSessionIdReviewsReviewIdRouteChildren {
  BooksBookIdSessionsSessionIdReviewsReviewIdNewRoute: typeof BooksBookIdSessionsSessionIdReviewsReviewIdNewRoute
  BooksBookIdSessionsSessionIdReviewsReviewIdIndexRoute: typeof BooksBookIdSessionsSessionIdReviewsReviewIdIndexRoute
}

const BooksBookIdSessionsSessionIdReviewsReviewIdRouteChildren: BooksBookIdSessionsSessionIdReviewsReviewIdRouteChildren =
  {
    BooksBookIdSessionsSessionIdReviewsReviewIdNewRoute:
      BooksBookIdSessionsSessionIdReviewsReviewIdNewRoute,
    BooksBookIdSessionsSessionIdReviewsReviewIdIndexRoute:
      BooksBookIdSessionsSessionIdReviewsReviewIdIndexRoute,
  }

const BooksBookIdSessionsSessionIdReviewsReviewIdRouteWithChildren =
  BooksBookIdSessionsSessionIdReviewsReviewIdRoute._addFileChildren(
    BooksBookIdSessionsSessionIdReviewsReviewIdRouteChildren,
  )

interface BooksBookIdSessionsSessionIdRouteChildren {
  BooksBookIdSessionsSessionIdIndexRoute: typeof BooksBookIdSessionsSessionIdIndexRoute
  BooksBookIdSessionsSessionIdReviewsReviewIdRoute: typeof BooksBookIdSessionsSessionIdReviewsReviewIdRouteWithChildren
}

const BooksBookIdSessionsSessionIdRouteChildren: BooksBookIdSessionsSessionIdRouteChildren =
  {
    BooksBookIdSessionsSessionIdIndexRoute:
      BooksBookIdSessionsSessionIdIndexRoute,
    BooksBookIdSessionsSessionIdReviewsReviewIdRoute:
      BooksBookIdSessionsSessionIdReviewsReviewIdRouteWithChildren,
  }

const BooksBookIdSessionsSessionIdRouteWithChildren =
  BooksBookIdSessionsSessionIdRoute._addFileChildren(
    BooksBookIdSessionsSessionIdRouteChildren,
  )

interface BooksBookIdRouteChildren {
  BooksBookIdIndexRoute: typeof BooksBookIdIndexRoute
  BooksBookIdSessionsSessionIdRoute: typeof BooksBookIdSessionsSessionIdRouteWithChildren
}

const BooksBookIdRouteChildren: BooksBookIdRouteChildren = {
  BooksBookIdIndexRoute: BooksBookIdIndexRoute,
  BooksBookIdSessionsSessionIdRoute:
    BooksBookIdSessionsSessionIdRouteWithChildren,
}

const BooksBookIdRouteWithChildren = BooksBookIdRoute._addFileChildren(
  BooksBookIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  BooksBookIdRoute: BooksBookIdRouteWithChildren,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
